1v1 with pb schema

diff --git a/.github/workflows/buf.yaml b/.github/workflows/buf.yaml
--- a/.github/workflows/buf.yaml
+++ b/.github/workflows/buf.yaml
@@ -3,8 +3,6 @@ on:
   pull_request:
     branches:
       - "main"
-    paths:
-      - '**.proto'
 jobs:
   lint:
     name: lint
@@ -13,11 +11,11 @@ jobs:
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.ref }}
-      - uses: bufbuild/buf-setup-action@v1.12.0
+      - uses: bufbuild/buf-setup-action@v1.18.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
       - uses: bufbuild/buf-lint-action@v1
-  
+
   verify_formatting:
     name: verify_formatting
     runs-on: ubuntu-latest
@@ -25,37 +23,17 @@ jobs:
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.ref }}
-      - uses: bufbuild/buf-setup-action@v1.12.0
+      - uses: bufbuild/buf-setup-action@v1.18.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
       - name: Verify the code pushed in formatted
         run: |
           buf format -w
-          if git diff --quiet --exit-code ; then 
+          if git diff --quiet --exit-code ; then
             echo "Code is formatted!";
             exit 0
           else
             echo "Code isn't formatted!";
-            exit 1
-          fi
-  push_compiled_code:
-    name: push_compiled_code
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-      - uses: bufbuild/buf-setup-action@v1.12.0
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-      - name: verify if compiled code is pushed
-        run: |
-          # Check if new compiled code has been pushed
-          if git diff --name-only $(git branch --show-current)..origin/main | grep "gen/"; then
-            echo "Compiled files are pushed!"
-            exit 0
-          else
-            echo "Compiled files haven't been pushed!"
             exit 1
           fi
   verify_compiled_code:
@@ -65,22 +43,32 @@ jobs:
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.ref }}
-      - uses: bufbuild/buf-setup-action@v1.12.0
+      - uses: bufbuild/buf-setup-action@v1.18.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
       - name: verify generated code is not altered
         run: |
           BIN="/usr/local/bin" && \
-          VERSION="1.12.0" && \
+          VERSION="1.18.0" && \
             curl -sSL \
               "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" \
               -o "${BIN}/buf" && \
             chmod +x "${BIN}/buf"
+          
+          buf generate -o verify_compiled_code
+          if diff -qr gen verify_compiled_code/gen ; then
+            echo "generated code is valid";
+          else 
+            echo "There seem to be some extra/missing generated files!";
+            exit 1
+          fi
+          rm -rf verify_compiled_code/
+          
           buf generate
-
           if git diff --quiet --exit-code ; then 
             echo "Unaltered code has been pushed";
           else 
+            echo "Code pushed seems to be altered";
             exit 1
           fi
   breaking_action:
@@ -90,7 +78,7 @@ jobs:
       - uses: actions/checkout@v3
         with:
           ref: ${{ github.ref }}
-      - uses: bufbuild/buf-setup-action@v1.12.0
+      - uses: bufbuild/buf-setup-action@v1.18.0
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
       - uses: bufbuild/buf-breaking-action@v1
